#!/bin/bash

#My personal directory paths
mkdir ~/Documents/git
mkdir ~/Downloads/torrents
cp ~/dotfiles/xmodmap /etc/init.d/xmodmap
git config --global user.name "Joshua Dong"; git config --global user.email "jdong42@gmail.com"
