{ config, pkgs, lib, inputs, ... }:

{
  # Home Manager basic configuration
  home.username = "joshua";
  home.homeDirectory = "/home/joshua";
  home.stateVersion = "24.11";

  # Let Home Manager install and manage itself
  programs.home-manager.enable = true;

  # =========================================================================
  # Neovim
  # =========================================================================
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    withRuby = true;
    withPython3 = true;
    plugins = with pkgs.vimPlugins; [
      goyo-vim
    ];
    extraConfig = builtins.readFile ./dotfiles/nvim/init.vim;
  };

  # =========================================================================
  # Hyprland
  # =========================================================================
  wayland.windowManager.hyprland = {
    enable = true;
    # `extraConfig` is raw hyprlang text; `settings = {}` means HM generates
    # nothing of its own to clash with it. configType must stay "hyprlang":
    # HM's hyprland module now defaults configType from "hyprlang" to "lua" (for
    # stateVersion >= 26.05), and letting it flip to "lua" would try to
    # interpret our raw hyprlang extraConfig as Lua. Pinning it here both keeps
    # current behavior and silences the HM default-change warning.
    configType = "hyprlang";
    settings = {};
    extraConfig = builtins.readFile ./dotfiles/hypr/hyprland.conf;
  };

  # Hyprlock config (no native Home Manager module yet)
  home.file.".config/hypr/hyprlock.conf".source = ./dotfiles/hypr/hyprlock.conf;

  # --- Idle policy: owned by thinkpower, not by a checked-in dotfile --------
  # The idle ladder used to be dotfiles/hypr/hypridle.conf. It is now generated
  # from ~/work/thinkpower/config/policy.toml, which is the single place every
  # timeout and action is written down.
  #
  # mkOutOfStoreSymlink, NOT home.file: home.file would make policy.toml a
  # read-only /nix/store symlink and the tool could never write it.
  xdg.configFile."thinkpower/policy.toml".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/work/thinkpower/config/policy.toml";

  # tomlkit so edits rewrite policy.toml without destroying its comments.
  # withPackages because the TUI needs textual; the on/do/event subcommands
  # are stdlib-only, which is why they worked while `thinkpower` alone did not.
  #
  # Wrapper rather than a packaged derivation, deliberately: it points at the
  # working checkout so editing the tool takes effect without a rebuild. The
  # PATH is explicit because hypridle runs as a user service with a minimal
  # environment -- a bare `brightnessctl` fails there, and so does a
  # `#!/usr/bin/env bash` shebang, which is why this uses an absolute one.
  home.file.".local/bin/thinkpower" = {
    executable = true;
    text = ''
      #!${pkgs.bash}/bin/bash
      export PATH="${lib.makeBinPath [ pkgs.brightnessctl pkgs.systemd pkgs.hyprland ]}:$PATH"
      exec ${pkgs.python3.withPackages (ps: [ ps.textual ps.tomlkit ])}/bin/python3 -c \
        'import sys; sys.path.insert(0, "${config.home.homeDirectory}/work/thinkpower"); from thinkpower.cli import main; main()' "$@"
    '';
  };

  # Replaces services.hypridle.enable, whose unit cannot take -c.
  systemd.user.services.hypridle = {
    Unit = {
      Description = "Hyprland idle daemon (config generated by thinkpower)";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
      ConditionEnvironment = "WAYLAND_DISPLAY";
    };
    Service = {
      Type = "simple";
      # Regenerate on every start so a boot lands on the declared policy even
      # if nothing has run `thinkpower apply` since policy.toml changed.
      ExecStartPre = "%h/.local/bin/thinkpower apply --no-restart";
      ExecStart = "${pkgs.hypridle}/bin/hypridle -c %h/.local/state/thinkpower/hypridle.conf";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # Lock-screen wallpapers: the four frames of the macOS "Tahoe (Dynamic)"
  # desktop, extracted from the Apple HEIC (one 6016x3384 container holding
  # night/morning/day/evening; its 5th frame is a byte-identical copy of the
  # night bookend that makes Apple's cycle loop, so it is dropped). Downscaled
  # to 3840x2160 — exact 16:9 for the 1920x1080 eDP panel with headroom for
  # fractional scaling.
  home.file.".local/share/wallpapers/tahoe" = {
    source = ./wallpapers/tahoe;
    recursive = true;
  };

  # Picks the variant matching the current hour and repoints the
  # `tahoe-current.jpg` symlink that hyprlock.conf's background points at.
  # That link sits OUTSIDE the tahoe/ dir above, which is a read-only store
  # symlink and cannot be written into.
  home.file.".local/bin/lockscreen-wallpaper" = {
    source = ./dotfiles/hypr/lockscreen-wallpaper.sh;
    executable = true;
  };

  # Fires a dunst OSD with the new brightness % on each change (see the script),
  # so brightness matches the volume popups pasystray shows. Wired to the
  # XF86MonBrightness keys (hyprland.conf) and the waybar backlight scroll.
  home.file.".local/bin/brightness-osd" = {
    source = ./dotfiles/hypr/brightness-osd.sh;
    executable = true;
  };

  # hyprlock as a managed user service so a crashed locker auto-respawns and
  # reattaches to the surviving session-lock surface (allow_session_lock_restore).
  # Triggered by hypridle's lock_cmd; not auto-started at login.
  systemd.user.services.hyprlock = {
    Unit = {
      Description = "Hyprlock screen locker";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      # Re-pick the time-of-day wallpaper on EVERY lock. This unit is the one
      # choke point all lock paths funnel through — hypridle's 300s timeout,
      # before_sleep_cmd on suspend, manual `loginctl lock-session`, and the
      # after_sleep_cmd `try-restart` that re-arms the fingerprint reader on
      # resume — so a laptop suspended at noon and opened at midnight comes
      # back to the night variant. `-` prefix: a failure here must never block
      # the locker from starting, since that would leave the session unlocked.
      ExecStartPre = "-%h/.local/bin/lockscreen-wallpaper";
      ExecStart = "${pkgs.hyprlock}/bin/hyprlock";
      Restart = "on-failure";
      RestartSec = 1;
      StartLimitBurst = 10;
    };
  };

  # =========================================================================
  # Dunst
  # =========================================================================
  # Dunst is D-Bus-activated (org.knopwob.dunst.service), not exec-once'd, so
  # a rebuild alone won't restyle a running daemon: `dunstctl reload` (or
  # pkill dunst) after switching. Styling rationale lives in the dunstrc.
  home.file.".config/dunst/dunstrc".source = ./dotfiles/dunst/dunstrc;

  # =========================================================================
  # Waybar
  # =========================================================================
  # Use original config files with proper FontAwesome unicode
  home.file.".config/waybar/config".source = ./dotfiles/waybar/config.jsonc;
  home.file.".config/waybar/style.css".source = ./dotfiles/waybar/style.css;

  # Backs the custom/netspeed module. Must be executable: waybar runs the
  # "exec" string through /bin/sh -c, so a non-executable file fails silently
  # as a permission error on the module rather than a startup error.
  home.file.".config/waybar/netspeed.sh" = {
    source = ./dotfiles/waybar/netspeed.sh;
    executable = true;
  };

  # Backs custom/diskio. Replaces the old iostat-based module, which could not
  # have worked: BusyBox iostat has no -x, and it matched ^sda on an NVMe box.
  home.file.".config/waybar/diskio.sh" = {
    source = ./dotfiles/waybar/diskio.sh;
    executable = true;
  };

  # Backs custom/ram: RAM% with swap folded into the background color.
  home.file.".config/waybar/ram.sh" = {
    source = ./dotfiles/waybar/ram.sh;
    executable = true;
  };

  # Tailscale's own logo (client/systray/tailscale.svg, BSD-3-Clause), the
  # background rect stripped and rendered to PNG in two states.
  home.file.".config/waybar/icons" = {
    source = ./dotfiles/waybar/icons;
    recursive = true;
  };

  # Backs image#tailscale. Reads `tailscale status --json` unprivileged.
  home.file.".config/waybar/tailscale.sh" = {
    source = ./dotfiles/waybar/tailscale.sh;
    executable = true;
  };

  # Backs custom/language. Replaces waybar's hyprland/language module, which
  # has no tooltip support, so the switch hotkey could not be shown on hover.
  home.file.".config/waybar/language.sh" = {
    source = ./dotfiles/waybar/language.sh;
    executable = true;
  };

  # Enable waybar package (but not the systemd service, since we start it from Hyprland)
  programs.waybar.enable = false;

  # =========================================================================
  # Tmux
  # =========================================================================
  programs.tmux = {
    enable = true;
    extraConfig = builtins.readFile ./dotfiles/tmux/tmux.conf;
  };

  # =========================================================================
  # Bash
  # =========================================================================
  programs.bash = {
    enable = true;
    historySize = 500;
    historyFileSize = 90000;

    bashrcExtra = ''
      # Only run interactive shell stuff if we're interactive
      if [[ $- == *i* ]]; then
        # Enable bash programmable completion features in interactive shells
        if [ -f /usr/share/bash-completion/bash_completion ]; then
        	. /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
        	. /etc/bash_completion
        fi

        # Disable the bell
        bind "set bell-style visible"

        # Append to history after each command
        PROMPT_COMMAND='history -a'

        # Ignore case on auto-completion
        bind "set completion-ignore-case on"

        # Show auto-completion list automatically, without double tab
        bind "set show-all-if-ambiguous On"

        # Starship prompt (managed by Home Manager)
        eval "$(starship init bash)"

        # NOTE: nvm was removed on 2026-08-19. It prepended
        # ~/.nvm/versions/node/<v>/bin to PATH in interactive shells only,
        # which outranked /run/current-system/sw/bin and let ANY writer to
        # that dir shadow a nix-managed binary. Claude Code's self-updater
        # did exactly that twice (2026-08-18 as joshua, 2026-08-19 as root,
        # leaving root-owned files in $HOME). Node now comes from nodejs_22
        # in packages.nix, and per-project versions come from a devshell +
        # direnv (programs.direnv below) -- e.g. ~/work/temi pins nodejs_24
        # in its own flake.nix to match its .nvmrc.
      fi
    '';

    # --icons=auto, NOT a bare --icons. eza made the flag's WHEN value optional
    # (always|auto|never), so a bare `--icons` swallows the next argument as its
    # value and `ls some/path/` dies with "invalid value ... for '--icons'".
    # The = form binds the value to the flag and leaves paths alone.
    shellAliases = {
      ls = "eza --icons=auto";
      ll = "eza -l --icons=auto";
      la = "eza -la --icons=auto";
    };
  };

  # =========================================================================
  # dconf
  # =========================================================================
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      # Chrome (native Wayland) reads this GNOME setting via the GTK settings
      # portal even outside GNOME, and treats "unset" as disabled — which
      # silently kills middle-click primary-selection paste in the browser
      # while it works everywhere else. Must be explicitly true on Hyprland.
      gtk-enable-primary-paste = true;
    };
  };

  # =========================================================================
  # Git
  # =========================================================================
  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "Joshua Dong";
        email = "jdong42@gmail.com";
      };
      safe = {
        directory = "/etc/nixos";
      };
    };

    ignores = [
      "**/.claude/settings.local.json"
    ];
  };

  # =========================================================================
  # Starship
  # =========================================================================
  home.file.".config/starship.toml".source = ./dotfiles/starship.toml;
  programs.starship = {
    enable = true;
    enableBashIntegration = false;  # We handle init manually in bashrcExtra
  };

  # =========================================================================
  # Fuzzel Launcher
  # =========================================================================
  home.file.".config/fuzzel/fuzzel.ini".source = ./dotfiles/fuzzel/fuzzel.ini;

  # =========================================================================
  # Foot Terminal
  # =========================================================================
  home.file.".config/foot/foot.ini".source = ./dotfiles/foot/foot.ini;
  programs.foot.enable = true;

  # =========================================================================
  # Brave — force XWayland to restore middle-click (primary-selection) paste
  # =========================================================================
  # Symptom (2026-06): selecting text in foot and middle-clicking into Brave
  # stopped pasting (foot->foot still works). Cause: a Brave update started
  # auto-running under native Wayland (Ozone). Chromium-family browsers do not
  # implement primary-selection PASTE under native Wayland, so middle-click
  # into Brave does nothing; under XWayland, XWayland bridges X11 PRIMARY and
  # it works. We don't set NIXOS_OZONE_WL, so the Nix wrapper passes no
  # --ozone-platform flag and Brave picks Wayland on its own — pin it to x11.
  # Brave reads ~/.config/brave-flags.conf at launch (Chromium flags-file
  # convention). To go back to native Wayland later, delete this / set
  # --ozone-platform=wayland (and accept middle-paste stays broken upstream).
  home.file.".config/brave-flags.conf".text = ''
    --ozone-platform=x11
  '';
  # Chrome keeps the x11 pin above (middle-click paste is wanted here), which
  # rules out the Wayland path where Chromium turns VAAPI on by default. Under
  # X11/GL the decoder is behind VaapiVideoDecodeLinuxGL instead, so it has to
  # be asked for explicitly. Verify at chrome://gpu -- "Video Decode" should
  # read "Hardware accelerated". Note this covers H.264/VP9 only: UHD 620 has
  # no AV1 decode block, so AV1 (much of YouTube) still lands on the CPU.
  home.file.".config/chrome-flags.conf".text = ''
    --ozone-platform=x11
    --enable-features=VaapiVideoDecodeLinuxGL
  '';

  # =========================================================================
  # Font Configuration
  # =========================================================================
  fonts.fontconfig.enable = true;

  # Disable antialiasing for the bitmap-identity fonts so they render as
  # pixels, not smoothed outlines. Applies to gohufont, the bitmap face.
  xdg.configFile."fontconfig/conf.d/75-disable-gohufont-antialiasing.conf".text = ''
    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
    <fontconfig>
      <description>Disable anti-aliasing for gohufont bitmap font</description>
      <match target="font">
        <test name="family" compare="eq">
          <string>gohufont</string>
        </test>
        <edit name="antialias" mode="assign">
          <bool>false</bool>
        </edit>
        <edit name="hinting" mode="assign">
          <bool>true</bool>
        </edit>
        <edit name="hintstyle" mode="assign">
          <const>hintfull</const>
        </edit>
      </match>
    </fontconfig>
  '';

  # =========================================================================
  # Misc Programs
  # =========================================================================
  programs.direnv = {
    enable = true;
    enableBashIntegration = true;
    nix-direnv.enable = true;
  };

  # =========================================================================
  # Cursor Theme
  # =========================================================================
  home.sessionVariables = {
    XCURSOR_THEME = "McMojave";
    XCURSOR_SIZE = "48";
    HYPRCURSOR_THEME = "McMojave";
    HYPRCURSOR_SIZE = "48";

    # Claude Code (and other Node CLIs using the `open` package) launch a
    # browser via $BROWSER, NOT xdg-open. With $BROWSER unset and no
    # x-www-browser/www-browser/sensible-browser on PATH, the fallback chain
    # is empty and browser-based OAuth logins silently fail — even though
    # plain `xdg-open` works. Point $BROWSER at xdg-open so it honors the
    # same default-browser (brave-browser.desktop) setting that already works.
    BROWSER = "xdg-open";

    # NOTE: the Claude Code auto-updater kill switch (DISABLE_AUTOUPDATER +
    # DISABLE_UPDATES) moved to configuration.nix `environment.variables` on
    # 2026-08-19. Home Manager only covers joshua, but root has its own
    # ~/.claude.json and root's claude self-updated into joshua's nvm dir.
    # It has to be system-wide to hold. See the comment there.
  };

  # =========================================================================
  # User Packages
  # =========================================================================
  home.packages = with pkgs; [
    # McMojave hyprcursor theme, with hotspots rescaled. Upstream
    # (libadoxon/mcmojave-hyprcursor, unmaintained since 2024-08) normalized
    # its pixel hotspots by 24 while the SVG canvases are 32x32, so every
    # hotspot is 4/3 too far from the origin. Shapes like right_ptr (1.17)
    # even land OUTSIDE the image, so clicks register up to a full cursor
    # width away from the visible tip. Verified against the SVGs: right_ptr's
    # tip is at pixel 28 of 32 (0.875) and meta.hl says 1.17 = 28/24.
    # Multiplying every hotspot by 24/32 = 0.75 restores the intended pixels.
    # Upstream's installPhase runs hyprcursor-util directly on $src (the shape
    # meta.hl files end up zipped inside the compiled .hlc archives), so the
    # rescale has to happen on a writable copy of the source BEFORE compiling.
    (inputs.mcmojave-hyprcursor.packages.${pkgs.stdenv.hostPlatform.system}.default.overrideAttrs (old: {
      pname = old.pname + "-hotspot-fix";
      installPhase = ''
        runHook preInstall

        cp -r $src src-fixed
        chmod -R u+w src-fixed
        find src-fixed -name meta.hl | while read -r f; do
          awk '
            $1 == "hotspot_x" || $1 == "hotspot_y" { printf "%s = %.4f\n", $1, $3 * 0.75; next }
            { print }
          ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
        done

        mkdir -p $out/share/icons/
        hyprcursor-util --create src-fixed -o $out/share/icons/

        runHook postInstall
      '';
    }))
  ];
}
