#!/bin/bash


link ~/dotfiles/vim/.vimrc ~/.vimrc;
mkdir ~/.xmonad/
link ~/dotfiles/xmonad/.xmonad/xmonad.hs ~/.xmonad/xmonad.hs;
link ~/dotfiles/xmobar/.xmobarrc ~/.xmobarrc;
link ~/dotfiles/xmodmap/.xmodmap ~/.Xmodmap;
while true; do
    read -p "Use Debian aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.debian_aliases ~/.bash_aliases; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Use Ubuntu aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.bash_aliases ~/.debian_aliases; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


