#!/bin/bash
while true; do
    read -p "Delete current .vimrc, .xmonad, .xmobarrc, .Xmodmap, .bash_aliases?" yn
    case $yn in
        [Yy]* ) rm -rf ~/.xmonad/; rm ~/.vimrc; rm ~/.xmobarrc; rm ~/.Xmodmap; rm ~/.bash_aliases; rm ~/.rtorrent.rc; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
link ~/dotfiles/vim/.vimrc ~/.vimrc;
mkdir ~/.xmonad/
link ~/dotfiles/xmonad/.xmonad/xmonad.hs ~/.xmonad/xmonad.hs;
link ~/dotfiles/xmobar/.xmobarrc ~/.xmobarrc;
link ~/dotfiles/xmodmap/.xmodmap ~/.Xmodmap;
xmodmap ~/.Xmodmap;
link ~/dotfiles/rtorrent/.rtorrent.rc ~/.rtorrent.rc;
while true; do
    read -p "Use Debian aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.debian_aliases ~/.bash_aliases; source ~/.bash_aliases; exit;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Use Ubuntu aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.bash_aliases ~/.debian_aliases; source ~/.bash_aliases; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
