#!/bin/bash


link ~/dotfiles/vim/.vimrc ~/.vimrc;
link ~/dotfiles/xmonad/.xmonad/ ~/.xmonad/;
link ~/dotfiles/xmobar/.xmobarrc ~/.xmobarrc;
while true; do
    read -p "Use Debian aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.debian_aliases ~/.debian_aliases; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Use Ubuntu aliases?" yn
    case $yn in
        [Yy]* ) link ~/dotfiles/bash_aliases/.bash_aliases ~/.debian_aliases; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


