#!/bin/bash

while true; do
    read -p "Setup vundle for vim plugins? " yn
    case $yn in
        [Yy]* ) add_vundle; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done

function add_vundle() {
    mkdir -p ~/.vim/autoload;
    if git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle > /dev/null
    then
        echo "Added vundle."
    else
        echo "~/.vim/bundle already exists."
    fi
    if grep -q "vundle" ~/.vimrc
    then
        echo "Vundle config already detected in ~/.vimrc."
    else
        echo "Modifying ~/.vimrc to use vundle..."

        echo "set nocompatible" >> /tmp/.vimrcTEMP
        echo "filetype off" >> /tmp/.vimrcTEMP
        echo "set rtp+=~/.vim/bundle/vundle" >> /tmp/.vimrcTEMP
        echo "call vundle#rc()" >> /tmp/.vimrcTEMP
        echo "Bundle 'gmarick/vundle'" >> /tmp/.vimrcTEMP
        echo "filetype plugin indent on" >> /tmp/.vimrcTEMP

        cat ~/.vimrc >> /tmp/.vimrcTEMP 
        mv /tmp/.vimrcTEMP ~/.vimrc
    fi
