---
- name: Install packages
  hosts: all
  tasks: 

    - name: basic packages
      pacman:
          name: git,bash,tmux,htop,tree,nmap,keychain,openssh
          state: latest

    - name: opinionated packages
      pacman:
          name: fish,macchanger
          state: latest

    - name: gui packages
      pacman:
          name: wayland,dmenu,alacritty,sway
          state: latest


  #     - name: gui packages
  #       pacman:
  #           name: xorg-server,xorg-xinit,xorg-xrandr,
  #           state: latest


      # yaourt -S culmus ttf-paratype ttf-google-fonts-git all-repository-fonts --noconfirm
      # 
      # yaourt -S \
      #     stow \
      #     wpa_supplicant \
      #     macchanger \
      #     git \
      #     cmake \
      #     zsh \
      #     zsh-syntax-highlighting \
      #     zsh-completions \
      #     dialog \
      #     xorg-server \
      #     xorg-xinit \
      #     xorg-xrandr \
      #     dmenu \
      #     conky \
      #     compton \
      #     keychain \
      #     termite \
      #     vim \
      #     ntp \
      #     openssh \
      #     htop \
      #     tmux \
      #     i3-wm \
      #     i3lock \
      #     nmap \
      #     keepass \
      #     imagemagick \
      #     evince
 

# ERROR! The field 'remote_user' is supposed to be a string type, however the incoming data structure is a <class 'ansible.parsing.yaml.objects.AnsibleMapping'>


# - name: Create a login user
#   user:
#     name: joshua
#     password: '$6$0vYbwl4.T/hdXIEn$y0TsbuWRJwJ6ttTU139WuJtA1EjPmz5hbW/bcCHMXA7AMz7njN2pG9XbGoCJl0vIJba0Vp6IZl0PVG1gbj.Go/'
#     groups:
#         - docker
#         - sudo
#     state: present
#     shell: /bin/fish
#     system: no
#     createhome: yes
#     # home: /home/joshua
