---
- name: Setup users and groups
  hosts: all
  tasks: 

    - name: basic packages
      pacman:
          name: git,bash,tmux,htop,tree,nmap,keychain,openssh
          state: latest

    - name: opinionated packages
      pacman:
          name: fish,macchanger
          state: latest

    - name: gui packages
      pacman:
          name: wayland,dmenu,alacritty,sway
          state: latest


