#!/bin/bash

#My personal directory paths
while true; do
    read -p "Make git folder and torrent folder? " yn
    case $yn in
        [Yy]* ) mkdir -p ~/Documents/git; mkdir -p ~/Downloads/torrents; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
#Set caps to ctrl
while true; do
    read -p "Rebind CAPS_LOCK to CTRL? " yn
    case $yn in
        [Yy]* ) cp ~/dotfiles/xmodmap /etc/init.d/xmodmap; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
#Set git global configs
echo "Setting git config...";
git config --global color.ui always; 
read -p "Git global name: " name;
read -p "Git global email: " email;
git config --global user.name $name;
git config --global user.email $email;
