#!/bin/bash
apt-get upgrade && apt-get update
apt-get install -y make curl xclip g++ htop netcat;
apt-get install -y vim;
apt-get install -y git git-core;
apt-get install -y python-pip build-essential python-dev ipython;
pip install distribute requests;
pip install --upgrade distribute 
echo "Installing optional packages...";
while true; do
    read -p "Install openJDK and openJRE? " yn
    case $yn in
        [Yy]* ) apt-get install -y openjdk-7-jre openjdk-7-jdk; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Install xmonad with xmobar and suckless-tools? " yn
    case $yn in
        [Yy]* ) apt-get install -y xmonad suckless-tools xmobar; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Install rtorrent? " yn
    case $yn in
        [Yy]* ) apt-get install -y rtorrent; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Install ssl and apache? " yn
    case $yn in
        [Yy]* ) apt-get install -y libssl-dev apache2-utils; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
while true; do
    read -p "Install sdl 1 dev tools? " yn
    case $yn in
        [Yy]* ) apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
