#!/bin/bash

#My personal directory paths
while true; do
    read -p "Make git folder and torrent folder? " yn
    case $yn in
        [Yy]* ) mkdir -p ~/Documents/git; mkdir -p ~/Downloads/torrents; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
