---
- name: install git
  become: yes
  pacman:
    name: git

- name: use stow for configuration
  become: yes
  become_user: "{{ username }}"
  stow:
    state: present
    package: git
    dir: '$HOME/.dotfiles/stow/'
    target: '$HOME'

- name: Set user email
  community.general.git_config:
    name: user.email 
    value: "{{ email }}"
    scope: global
  become_user: "{{ username }}"

- name: Set user name
  community.general.git_config:
    name: user.name
    value: "{{ fullname }}"
    scope: global
  become_user: "{{ username }}"
