---
- name: install wofi
  become: yes
  pacman:
    name: wofi

- name: use stow for configuration
  become: yes
  become_user: "{{ username }}"
  stow:
    state: present
    package: wofi
    dir: '$HOME/.dotfiles/stow/'
    target: '$HOME/.config'
